"""stack — generated by ea bind"""
import ctypes as _ct
import numpy as _np
from pathlib import Path as _Path

_lib = _ct.CDLL(str(_Path(__file__).with_name("libstack.so")))

_lib.accumulate_f32x8.argtypes = [_ct.POINTER(_ct.c_float), _ct.POINTER(_ct.c_float), _ct.c_int32]
_lib.accumulate_f32x8.restype = None

def accumulate_f32x8(acc: _np.ndarray, frame: _np.ndarray):
    """accumulate_f32x8(acc: *mut f32, frame: *restrict f32, len: i32) -> void"""
    if acc.dtype != _np.float32:
        raise TypeError("acc: expected float32")
    if frame.dtype != _np.float32:
        raise TypeError("frame: expected float32")
    _lib.accumulate_f32x8(
        acc.ctypes.data_as(_ct.POINTER(_ct.c_float)),
        frame.ctypes.data_as(_ct.POINTER(_ct.c_float)),
        _ct.c_int32(frame.size)
    )

_lib.accumulate_batch4_f32x8.argtypes = [_ct.POINTER(_ct.c_float), _ct.POINTER(_ct.c_float), _ct.POINTER(_ct.c_float), _ct.POINTER(_ct.c_float), _ct.POINTER(_ct.c_float), _ct.c_int32]
_lib.accumulate_batch4_f32x8.restype = None

def accumulate_batch4_f32x8(acc: _np.ndarray, f0: _np.ndarray, f1: _np.ndarray, f2: _np.ndarray, f3: _np.ndarray):
    """accumulate_batch4_f32x8(acc: *mut f32, f0: *restrict f32, f1: *restrict f32, f2: *restrict f32, f3: *restrict f32, len: i32) -> void"""
    if acc.dtype != _np.float32:
        raise TypeError("acc: expected float32")
    if f0.dtype != _np.float32:
        raise TypeError("f0: expected float32")
    if f1.dtype != _np.float32:
        raise TypeError("f1: expected float32")
    if f2.dtype != _np.float32:
        raise TypeError("f2: expected float32")
    if f3.dtype != _np.float32:
        raise TypeError("f3: expected float32")
    _lib.accumulate_batch4_f32x8(
        acc.ctypes.data_as(_ct.POINTER(_ct.c_float)),
        f0.ctypes.data_as(_ct.POINTER(_ct.c_float)),
        f1.ctypes.data_as(_ct.POINTER(_ct.c_float)),
        f2.ctypes.data_as(_ct.POINTER(_ct.c_float)),
        f3.ctypes.data_as(_ct.POINTER(_ct.c_float)),
        _ct.c_int32(f3.size)
    )

_lib.accumulate_batch8_f32x8.argtypes = [_ct.POINTER(_ct.c_float), _ct.POINTER(_ct.c_float), _ct.POINTER(_ct.c_float), _ct.POINTER(_ct.c_float), _ct.POINTER(_ct.c_float), _ct.POINTER(_ct.c_float), _ct.POINTER(_ct.c_float), _ct.POINTER(_ct.c_float), _ct.POINTER(_ct.c_float), _ct.c_int32]
_lib.accumulate_batch8_f32x8.restype = None

def accumulate_batch8_f32x8(acc: _np.ndarray, f0: _np.ndarray, f1: _np.ndarray, f2: _np.ndarray, f3: _np.ndarray, f4: _np.ndarray, f5: _np.ndarray, f6: _np.ndarray, f7: _np.ndarray):
    """accumulate_batch8_f32x8(acc: *mut f32, f0: *restrict f32, f1: *restrict f32, f2: *restrict f32, f3: *restrict f32, f4: *restrict f32, f5: *restrict f32, f6: *restrict f32, f7: *restrict f32, len: i32) -> void"""
    if acc.dtype != _np.float32:
        raise TypeError("acc: expected float32")
    if f0.dtype != _np.float32:
        raise TypeError("f0: expected float32")
    if f1.dtype != _np.float32:
        raise TypeError("f1: expected float32")
    if f2.dtype != _np.float32:
        raise TypeError("f2: expected float32")
    if f3.dtype != _np.float32:
        raise TypeError("f3: expected float32")
    if f4.dtype != _np.float32:
        raise TypeError("f4: expected float32")
    if f5.dtype != _np.float32:
        raise TypeError("f5: expected float32")
    if f6.dtype != _np.float32:
        raise TypeError("f6: expected float32")
    if f7.dtype != _np.float32:
        raise TypeError("f7: expected float32")
    _lib.accumulate_batch8_f32x8(
        acc.ctypes.data_as(_ct.POINTER(_ct.c_float)),
        f0.ctypes.data_as(_ct.POINTER(_ct.c_float)),
        f1.ctypes.data_as(_ct.POINTER(_ct.c_float)),
        f2.ctypes.data_as(_ct.POINTER(_ct.c_float)),
        f3.ctypes.data_as(_ct.POINTER(_ct.c_float)),
        f4.ctypes.data_as(_ct.POINTER(_ct.c_float)),
        f5.ctypes.data_as(_ct.POINTER(_ct.c_float)),
        f6.ctypes.data_as(_ct.POINTER(_ct.c_float)),
        f7.ctypes.data_as(_ct.POINTER(_ct.c_float)),
        _ct.c_int32(f7.size)
    )

_lib.accumulate_batch8_f32x8_nt.argtypes = [_ct.POINTER(_ct.c_float), _ct.POINTER(_ct.c_float), _ct.POINTER(_ct.c_float), _ct.POINTER(_ct.c_float), _ct.POINTER(_ct.c_float), _ct.POINTER(_ct.c_float), _ct.POINTER(_ct.c_float), _ct.POINTER(_ct.c_float), _ct.POINTER(_ct.c_float), _ct.c_int32]
_lib.accumulate_batch8_f32x8_nt.restype = None

def accumulate_batch8_f32x8_nt(acc: _np.ndarray, f0: _np.ndarray, f1: _np.ndarray, f2: _np.ndarray, f3: _np.ndarray, f4: _np.ndarray, f5: _np.ndarray, f6: _np.ndarray, f7: _np.ndarray):
    """accumulate_batch8_f32x8_nt(acc: *mut f32, f0: *restrict f32, f1: *restrict f32, f2: *restrict f32, f3: *restrict f32, f4: *restrict f32, f5: *restrict f32, f6: *restrict f32, f7: *restrict f32, len: i32) -> void"""
    if acc.dtype != _np.float32:
        raise TypeError("acc: expected float32")
    if f0.dtype != _np.float32:
        raise TypeError("f0: expected float32")
    if f1.dtype != _np.float32:
        raise TypeError("f1: expected float32")
    if f2.dtype != _np.float32:
        raise TypeError("f2: expected float32")
    if f3.dtype != _np.float32:
        raise TypeError("f3: expected float32")
    if f4.dtype != _np.float32:
        raise TypeError("f4: expected float32")
    if f5.dtype != _np.float32:
        raise TypeError("f5: expected float32")
    if f6.dtype != _np.float32:
        raise TypeError("f6: expected float32")
    if f7.dtype != _np.float32:
        raise TypeError("f7: expected float32")
    _lib.accumulate_batch8_f32x8_nt(
        acc.ctypes.data_as(_ct.POINTER(_ct.c_float)),
        f0.ctypes.data_as(_ct.POINTER(_ct.c_float)),
        f1.ctypes.data_as(_ct.POINTER(_ct.c_float)),
        f2.ctypes.data_as(_ct.POINTER(_ct.c_float)),
        f3.ctypes.data_as(_ct.POINTER(_ct.c_float)),
        f4.ctypes.data_as(_ct.POINTER(_ct.c_float)),
        f5.ctypes.data_as(_ct.POINTER(_ct.c_float)),
        f6.ctypes.data_as(_ct.POINTER(_ct.c_float)),
        f7.ctypes.data_as(_ct.POINTER(_ct.c_float)),
        _ct.c_int32(f7.size)
    )

_lib.scale_f32x8.argtypes = [_ct.POINTER(_ct.c_float), _ct.POINTER(_ct.c_float), _ct.c_int32, _ct.c_float]
_lib.scale_f32x8.restype = None

def scale_f32x8(data: _np.ndarray, out: _np.ndarray, factor: float):
    """scale_f32x8(data: *restrict f32, out: *mut f32, len: i32, factor: f32) -> void"""
    if data.dtype != _np.float32:
        raise TypeError("data: expected float32")
    if out.dtype != _np.float32:
        raise TypeError("out: expected float32")
    _lib.scale_f32x8(
        data.ctypes.data_as(_ct.POINTER(_ct.c_float)),
        out.ctypes.data_as(_ct.POINTER(_ct.c_float)),
        _ct.c_int32(out.size),
        _ct.c_float(float(factor))
    )

_lib.frame_stats.argtypes = [_ct.POINTER(_ct.c_float), _ct.c_int32, _ct.POINTER(_ct.c_float), _ct.POINTER(_ct.c_float), _ct.POINTER(_ct.c_float)]
_lib.frame_stats.restype = None

def frame_stats(data: _np.ndarray, out_min: _np.ndarray, out_max: _np.ndarray, out_sum: _np.ndarray):
    """frame_stats(data: *restrict f32, len: i32, out_min: *mut f32, out_max: *mut f32, out_sum: *mut f32) -> void"""
    if data.dtype != _np.float32:
        raise TypeError("data: expected float32")
    if out_min.dtype != _np.float32:
        raise TypeError("out_min: expected float32")
    if out_max.dtype != _np.float32:
        raise TypeError("out_max: expected float32")
    if out_sum.dtype != _np.float32:
        raise TypeError("out_sum: expected float32")
    _lib.frame_stats(
        data.ctypes.data_as(_ct.POINTER(_ct.c_float)),
        _ct.c_int32(data.size),
        out_min.ctypes.data_as(_ct.POINTER(_ct.c_float)),
        out_max.ctypes.data_as(_ct.POINTER(_ct.c_float)),
        out_sum.ctypes.data_as(_ct.POINTER(_ct.c_float))
    )

