"""sobel — generated by ea bind"""
import ctypes as _ct
import numpy as _np
from pathlib import Path as _Path

_lib = _ct.CDLL(str(_Path(__file__).with_name("libsobel.so")))

_lib.sobel.argtypes = [_ct.POINTER(_ct.c_float), _ct.POINTER(_ct.c_float), _ct.c_int32, _ct.c_int32]
_lib.sobel.restype = None

def sobel(input: _np.ndarray, out: _np.ndarray, width: int, height: int):
    """sobel(input: *restrict f32, out: *mut f32, width: i32, height: i32) -> void"""
    if input.dtype != _np.float32:
        raise TypeError("input: expected float32")
    if out.dtype != _np.float32:
        raise TypeError("out: expected float32")
    _lib.sobel(
        input.ctypes.data_as(_ct.POINTER(_ct.c_float)),
        out.ctypes.data_as(_ct.POINTER(_ct.c_float)),
        _ct.c_int32(int(width)),
        _ct.c_int32(int(height))
    )

